apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: mateapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: todoapp
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "30m"
        image: ikulyk404/todoapp:3.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
